version: '3.8'
services:
  stats-server:
    build: stats/stats-server
    container_name: stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/ewm-stats
      SPRING_DATASOURCE_USERNAME: stat
      SPRING_DATASOURCE_PASSWORD: stat
    depends_on:
      stats-db:
        condition: service_healthy
    networks:
      - app-network

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_USER: stat
      POSTGRES_PASSWORD: stat
      POSTGRES_DB: ewm-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      retries: 10
      timeout: 5s
    volumes:
      - stats_db_data:/var/lib/postgresql/data # Добавляем том для stats-db
    networks:
      - app-network

  ewm-service:
    build: core/main-service
    container_name: main-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/ewm-database
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      ewm-db:
        condition: service_healthy
    networks:
      - app-network

  ewm-db:
    container_name: ewm-db
    image: postgres:16.1
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: ewm-database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 5s
      retries: 10
      timeout: 5s
    volumes:
      - ewm_db_data:/var/lib/postgresql/data # Добавляем том для ewm-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ewm_db_data: # Определяем том для ewm-db
  stats_db_data: # Определяем том для stats-db