logging:
  level:
    ru.yandex.practicum.telemetry: TRACE
    org:
      springframework: ERROR
      apache.kafka: INFO

server:
  port: 0

spring:
  application:
    name: aggregator
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:6543/ewm-database
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

kafka:
  consumer:
    properties:
      bootstrap.servers: localhost:9092
      group.id: aggregator-group
      auto.offset.reset: earliest
      enable.auto.commit: false
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: kafka.deserialization.UserActionDeserializer
    topic: stats.user-actions.v1
  producer:
    properties:
      bootstrap.servers: localhost:9092
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: kafka.serialization.AvroSerializer
    topic: stats.events-similarity.v1