DROP TABLE IF EXISTS participation_request;

CREATE TABLE IF NOT EXISTS participation_request
(
    id       BIGINT      NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id  BIGINT      NOT NULL,
    event_id BIGINT      NOT NULL,
    status   VARCHAR(50) NOT NULL,
    created  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
--    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
--    FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT unique_user_event UNIQUE (user_id, event_id) -- Запрещает дублирующиеся заявки
);