spring:
  application:
    name: gateway-server
  config:
    import: "configserver:http://config-server:8888"
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.5
        max-attempts: 10

eureka:
  client:
    registryFetchIntervalSeconds: 5  # Обновлять реестр каждые 5 секунд
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5  # Отправлять heartbeat каждые 5 секунд
    leaseExpirationDurationInSeconds: 15  # Время до исключения из реестра