spring:
  application:
    name: ewm-service
  config:
    import: "configserver:http://config-server:8888"
  cloud:
    config:
      fail-fast: false
      retry:
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.5
        max-attempts: 10

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10

logging:
  level:
    org.springframework.boot.context.config: DEBUG