spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
        - id: ewm_service_route
          uri: lb://EWM-SERVICE
          predicates:
            - Path=/admin/**,/categories/**,/compilations/**,/events/**,/users/**
          filters:
            - StripPrefix=0
        - id: stats_service_route
          uri: lb://STATS-SERVER
          predicates:
            - Path=/stats/**,/hit/**
          filters:
            - StripPrefix=0
        - id: config_service_route
          uri: lb://CONFIG-SERVER
          predicates:
            - Path=/config/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.http.server.reactive: INFO

management:
  endpoints:
    web:
      exposure:
        include: "env,health,metrics"